const mongoose = require("mongoose");

const commonSettingsSchema = new mongoose.Schema(
  {
    companyName: { type: String },
    companyLogo: { type: String },
  },
  { _id: false, versionKey: false },
);

const functionalSettingsSchema = new mongoose.Schema(
  {
    need_employee_approval_for_po: {
      type: String,
      enum: ["no approval", "agent approval", "admin approval"],
      default: "admin approval",
    },
    dms_edit_mode_enabled: {
      type: Boolean,
      default: false,
    },
  },
  { _id: false, versionKey: false },
);

const configSchema = new mongoose.Schema(
  {
    centralPortalSettings: { type: mongoose.Schema.Types.Mixed },
    dmsSettings: { type: mongoose.Schema.Types.Mixed },
    commonSettings: commonSettingsSchema,
    functionalSettings: functionalSettingsSchema,
    autogeneratedCodePrefixSettings: { type: mongoose.Schema.Types.Mixed },
    centralPortalThemeSettings: { type: mongoose.Schema.Types.Mixed },
    dmsThemeSettings: { type: mongoose.Schema.Types.Mixed },
  },
  { timestamps: true, versionKey: false },
);

const Config = mongoose.model("Config", configSchema);

module.exports = Config;
