const mongoose = require("mongoose");

const LineItemSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Product",
    required: true,
  },
  uom: {
    type: String,
    enum: {
      values: ["pcs", "box"],
      message: "values allowed pcs/box",
    },
  },
  price: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Price",
    required: true,
  },
  inventoryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Inventory",
  },
  billQty: {
    type: Number,
    default: 0,
  },
  returnQty: {
    type: Number,
    default: 0,
  },
  grossAmt: {
    type: Number,
    default: 0,
  },
  schemeDisc: {
    type: Number,
    default: 0,
  },
  distributorDisc: {
    type: Number,
    default: 0,
  },
  distributorDiscUnit: {
    type: String,
    enum: ["percent", "amount"],
  },
  taxableAmt: {
    type: Number,
    default: 0,
  },
  totalCGST: {
    type: Number,
    default: 0,
  },
  totalSGST: {
    type: Number,
    default: 0,
  },
  totalIGST: {
    type: Number,
    default: 0,
  },
  netAmt: {
    type: Number,
    default: 0,
  },
  adjustmentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Transaction",
  },
  salesReturnRemark: {
    type: String,
    default: "", // sales return for invoice : invoice number
  },
});

const creditNoteSchema = new mongoose.Schema(
  {
    distributorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Distributor",
      required: true,
    },
    outletId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "OutletApproved",
      required: true,
    },
    salesReturnId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SalesReturn",
    },
    billId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Bill",
    },
    adjustmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Transaction",
    },
    lineItems: [LineItemSchema],
    creditNoteNo: {
      type: String,
      required: true, // autogenerated incremental unique number
    },
    amount: {
      type: Number,
      default: 0,
    },
    creditNoteCreationDate: {
      type: Date,
      default: Date.now,
    },
    creditNoteRemark: {
      type: String,
      default: "",
    },
    creditNoteType: {
      type: String,
      enum: ["With Reference", "Without Reference", "Manual Credit note"],
      default: "Manual Credit note",
    },
    adjustedBillIds: [
      {
        billId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Bill",
        },

        orderId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "OrderEntry",
        },
        type: {
          type: String,
          enum: ["Order_To_Bill", "Collection"],
        },
        collectionId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "LedgerCollection",
        },
        adjustedAmount: {
          type: Number,
          default: 0,
        },
      },
    ],
    creditNoteStatus: {
      type: String,
      enum: ["Pending", "Completely Adjusted"],
      default: "Pending",
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  },
);

const CreditNoteModel = mongoose.model("CreditNote", creditNoteSchema);

module.exports = CreditNoteModel;
