const mongoose = require("mongoose");

const LineItemSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Product",
    required: true,
  },
  uom: {
    type: String,
    enum: {
      values: ["pcs", "box"],
      message: "values allowed pcs/box",
    },
  },
  price: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Price",
    required: true,
  },
  inventoryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Inventory",
  },
  billQty: {
    type: Number,
    default: 0,
  },
  returnQty: {
    type: Number,
    default: 0,
  },
  grossAmt: {
    type: Number,
    default: 0,
  },
  schemeDisc: {
    type: Number,
    default: 0,
  },
  distributorDisc: {
    type: Number,
    default: 0,
  },
  distributorDiscUnit: {
    type: String,
    enum: ["percent", "amount"],
  },
  taxableAmt: {
    type: Number,
    default: 0,
  },
  totalCGST: {
    type: Number,
    default: 0,
  },
  totalSGST: {
    type: Number,
    default: 0,
  },
  totalIGST: {
    type: Number,
    default: 0,
  },
  netAmt: {
    type: Number,
    default: 0,
  },
  adjustmentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Transaction",
  },
  salesReturnRemark: {
    type: String,
    default: "", // sales return for invoice : invoice number
  },
});

const replacement = new mongoose.Schema(
  {
    distributorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Distributor",
      required: true,
    },
    outletId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "OutletApproved",
      required: true,
    },
    salesReturnId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SalesReturn",
    },
    billId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Bill",
    },
    adjustmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Transaction",
    },
    lineItems: [LineItemSchema],
    replacementNo: {
      type: String,
      required: true, // autogenerated incremental unique number
    },
    replacementDate: {
      type: Date,
      default: Date.now,
    },
    adjustedBillIds: [
      {
        billId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Bill",
        },
        adjustedQty: {
          type: Number,
          default: 0,
        },
      },
    ],
    status: {
      type: String,
      enum: ["Pending", "Completely Adjusted"],
      default: "Pending",
    },
    replacementType: {
      type: String,
      enum: ["With Reference", "Without Reference"],
      default: "Without Reference",
    },
    remark: {
      type: String,
      default: "",
    },
  },
  {
    timestamps: true,
  }
);

const Replacement = mongoose.model("Replacement", replacement);

module.exports = Replacement;
